### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by cinimodev** [Jocomol/newsboat_video_downloader#4]
Stumbled on this script and just wanna say thanks. I also like to read/view RSS feeds offline and manually using `yt-dlp` to do it is tedious. Some other tools exist, but your script makes it so easy. I am using Newsboat with FreshRSS and it grabs everything perfectly. I added some additional flags for `yt-dlp` and works like a charm. 

Thanks for your work!

**Comment by Jocomol** [comment]
Glad I could help, feel free to open pull requests!
